name: Run Python Script at Midnight

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 (midnight) everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run your Python script
        run: python main.py

      - name: Commit
        run: |
          date > generated.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data"
          git push
        
        
